# Generated by Django 5.2.15 on 2026-07-04 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('categoria', models.CharField(max_length=60)),
                ('industria', models.CharField(max_length=60)),
                ('anio', models.PositiveIntegerField()),
                ('resultado', models.CharField(help_text='Resumen corto mostrado en las tarjetas de listado.', max_length=300)),
                ('resumen', models.TextField(help_text='Resumen largo mostrado en el detalle.')),
                ('es_ancla', models.BooleanField(default=False, verbose_name='Proyecto ancla')),
                ('imagen_card', models.ImageField(blank=True, null=True, upload_to='proyectos/cards/')),
                ('imagen_hero', models.ImageField(blank=True, null=True, upload_to='proyectos/hero/')),
                ('imagen_arquitectura', models.ImageField(blank=True, null=True, upload_to='proyectos/arquitectura/')),
                ('problema', models.TextField(blank=True)),
                ('solucion', models.TextField(blank=True)),
                ('arquitectura_texto', models.TextField(blank=True)),
                ('stack', models.CharField(blank=True, help_text='Tecnologías separadas por coma.', max_length=500)),
                ('web_url', models.URLField(blank=True, verbose_name='URL de demo')),
                ('github_url', models.URLField(blank=True, verbose_name='URL de GitHub')),
                ('notebook_url', models.URLField(blank=True, verbose_name='URL de notebook')),
                ('publicado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-anio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='proyectos/galeria/')),
                ('placeholder', models.CharField(blank=True, max_length=120)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='core.project')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=40)),
                ('etiqueta', models.CharField(max_length=80)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='core.project')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=40)),
                ('etiqueta', models.CharField(max_length=160)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.project')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasos', to='core.project')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
