# Generated by Django 5.2.15 on 2026-07-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=220)),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True)),
                ('pilar', models.CharField(choices=[('Arquitectura', 'Arquitectura'), ('Data Science e IA', 'Data Science e IA'), ('Pensamiento Sistémico', 'Pensamiento Sistémico')], max_length=40)),
                ('extracto', models.TextField(help_text='Resumen corto mostrado en las tarjetas de listado.')),
                ('contenido', models.TextField(help_text='Cuerpo del artículo en formato Markdown.')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='blog/portadas/')),
                ('tags', models.CharField(blank=True, help_text='Temas separados por coma.', max_length=300)),
                ('fecha_publicacion', models.DateField()),
                ('lectura_min', models.PositiveIntegerField(default=5, verbose_name='Minutos de lectura')),
                ('publicado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fecha_publicacion', 'id'],
            },
        ),
    ]
