# Generated by Django 5.2.15 on 2026-07-08 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_texto', models.CharField(default='Tolerancia cero al error', max_length=100)),
                ('nombre', models.CharField(default='Carlos A. Jiménez Hirashi', max_length=150)),
                ('bio', models.TextField(verbose_name='Biografía corta (hero)')),
                ('cta_primario_texto', models.CharField(default='Hablemos', max_length=50)),
                ('cta_secundario_texto', models.CharField(default='Ver proyectos', max_length=50)),
                ('filosofia_titulo', models.CharField(default='Diseñar para que el error no exista', max_length=200)),
                ('filosofia_cita', models.TextField(verbose_name='Cita (blockquote)')),
                ('filosofia_texto', models.TextField(verbose_name='Texto de filosofía')),
                ('trayectoria_titulo', models.CharField(default='20+ años, dos disciplinas, un mismo estándar', max_length=200)),
                ('cta_final_titulo', models.CharField(default='¿Un sistema que no puede fallar?', max_length=200)),
                ('cta_final_texto', models.TextField(default='Hablemos de tu proyecto de datos, IA o automatización crítica.')),
                ('cta_final_boton_texto', models.CharField(default='Ir a contacto', max_length=50)),
            ],
            options={
                'verbose_name': 'Contenido de Sobre Mí',
                'verbose_name_plural': 'Contenido de Sobre Mí',
            },
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_texto', models.CharField(default='Tolerancia cero al error', max_length=100)),
                ('titulo', models.CharField(max_length=300, verbose_name='Título del hero')),
                ('lead', models.TextField(verbose_name='Texto del hero')),
                ('cta_primario_texto', models.CharField(default='Ver caso INS', max_length=50)),
                ('cta_secundario_texto', models.CharField(default='Ver proyectos', max_length=50)),
                ('caso_titulo', models.CharField(default='Caso ancla — Bioterio INS', max_length=200, verbose_name='Título del caso de estudio')),
                ('caso_anio', models.CharField(default='2015', max_length=10)),
                ('caso_problema', models.TextField(verbose_name='Problema')),
                ('caso_arquitectura', models.TextField(verbose_name='Arquitectura')),
                ('caso_resultado', models.TextField(help_text='Se permite HTML simple, ej. <b>negrita</b>.', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Contenido de Home',
                'verbose_name_plural': 'Contenido de Home',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(help_text='Nombre de ícono Lucide, ej: shield-check', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('entidad', models.CharField(max_length=150)),
                ('anio', models.CharField(max_length=10)),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certs', to='core.aboutcontent')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeCaseStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('etiqueta', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_stats', to='core.homecontent')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(help_text='Ej: 12, 20, 99.9')),
                ('sufijo', models.CharField(blank=True, help_text='Ej: +, %', max_length=5)),
                ('etiqueta', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=10)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.homecontent')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=150)),
                ('items', models.CharField(help_text='Habilidades separadas por coma.', max_length=500)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_groups', to='core.aboutcontent')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=150)),
                ('contexto', models.CharField(max_length=150)),
                ('logro', models.TextField()),
                ('orden', models.PositiveIntegerField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.aboutcontent')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
