# Generated by Django 5.2.15 on 2026-07-08 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutcontent_homecontent_certification_homecasestat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certification',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Certificación', 'verbose_name_plural': 'Certificaciones'},
        ),
        migrations.AlterModelOptions(
            name='homecasestat',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Estadística del caso', 'verbose_name_plural': 'Estadísticas del caso de estudio'},
        ),
        migrations.AlterModelOptions(
            name='homestat',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Estadística', 'verbose_name_plural': 'Estadísticas del hero'},
        ),
        migrations.AlterModelOptions(
            name='skillgroup',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Grupo de habilidades', 'verbose_name_plural': 'Habilidades técnicas'},
        ),
        migrations.AlterModelOptions(
            name='timelineentry',
            options={'ordering': ['orden', 'id'], 'verbose_name': 'Entrada de trayectoria', 'verbose_name_plural': 'Trayectoria (timeline)'},
        ),
    ]
