# Generated by Django 5.2.15 on 2026-07-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_certification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homecontent',
            name='caso_anio',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='caso_arquitectura',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='caso_problema',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='caso_resultado',
        ),
        migrations.RemoveField(
            model_name='homecontent',
            name='caso_titulo',
        ),
        migrations.DeleteModel(
            name='HomeCaseStat',
        ),
    ]
