# Generated by Django 5.2.15 on 2026-07-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_homecontent_caso_anio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='destacado_home',
            field=models.BooleanField(default=False, help_text='Se muestra en la sección "Del blog" del Home (máx. 3).', verbose_name='Destacado en Home'),
        ),
        migrations.AddField(
            model_name='project',
            name='destacado_home',
            field=models.BooleanField(default=False, help_text='Se muestra en la sección "Proyectos destacados" del Home (máx. 3).', verbose_name='Destacado en Home'),
        ),
    ]
