# Generated by Django 5.2.15 on 2026-07-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_destacado_home_project_destacado_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcontent',
            name='badge_texto',
            field=models.CharField(default='Tolerancia cero al error', help_text='Texto de la pastilla pequeña junto a la foto, arriba del nombre.', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='bio',
            field=models.TextField(help_text='Párrafo debajo del nombre, en la parte superior de la página.', verbose_name='Biografía corta (hero)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_final_boton_texto',
            field=models.CharField(default='Ir a contacto', help_text='Texto del botón de esa tarjeta final (lleva a Contacto).', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_final_texto',
            field=models.TextField(default='Hablemos de tu proyecto de datos, IA o automatización crítica.', help_text='Texto debajo del título, en la tarjeta de contacto final.'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_final_titulo',
            field=models.CharField(default='¿Un sistema que no puede fallar?', help_text='Título de la tarjeta de contacto al final de la página.', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_primario_texto',
            field=models.CharField(default='Hablemos', help_text='Texto del botón principal del hero (lleva a Contacto).', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='cta_secundario_texto',
            field=models.CharField(default='Ver proyectos', help_text='Texto del botón secundario del hero (lleva al listado de Proyectos).', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='filosofia_cita',
            field=models.TextField(help_text='Texto grande en cursiva, destacado con una línea vertical.', verbose_name='Cita (blockquote)'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='filosofia_texto',
            field=models.TextField(help_text='Párrafo largo debajo de la cita.', verbose_name='Texto de filosofía'),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='filosofia_titulo',
            field=models.CharField(default='Diseñar para que el error no exista', help_text='Título de la sección "01 · Filosofía".', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='nombre',
            field=models.CharField(default='Carlos A. Jiménez Hirashi', help_text='Nombre completo, título grande del hero.', max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutcontent',
            name='trayectoria_titulo',
            field=models.CharField(default='20+ años, dos disciplinas, un mismo estándar', help_text='Título de la sección "02 · Trayectoria" (arriba de la línea de tiempo).', max_length=200),
        ),
        migrations.AlterField(
            model_name='certification',
            name='anio',
            field=models.CharField(help_text='Año en que se obtuvo, ej: 2021.', max_length=10),
        ),
        migrations.AlterField(
            model_name='certification',
            name='color',
            field=models.CharField(choices=[('primary', 'Primary (azul)'), ('secondary', 'Secondary (morado)')], default='primary', help_text='Color del ícono y su fondo. Alterna primary/secondary para dar variedad visual.', max_length=10),
        ),
        migrations.AlterField(
            model_name='certification',
            name='entidad',
            field=models.CharField(help_text='Institución u organización que la emitió.', max_length=150),
        ),
        migrations.AlterField(
            model_name='certification',
            name='icono',
            field=models.CharField(help_text='Nombre exacto de un ícono de Lucide (ver lucide.dev/icons), ej: shield-check, network, cloud, brain-circuit.', max_length=50),
        ),
        migrations.AlterField(
            model_name='certification',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden de aparición (menor primero).'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='titulo',
            field=models.CharField(help_text='Nombre de la certificación.', max_length=200),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='badge_texto',
            field=models.CharField(default='Tolerancia cero al error', help_text='Texto de la pastilla pequeña arriba del título del hero.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='cta_primario_texto',
            field=models.CharField(default='Ver caso INS', help_text='Texto del botón principal del hero. Ese mismo botón se repite abajo, en la sección "Caso ancla".', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='cta_secundario_texto',
            field=models.CharField(default='Ver proyectos', help_text='Texto del botón secundario del hero (lleva siempre al listado de Proyectos).', max_length=50),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='lead',
            field=models.TextField(help_text='Párrafo debajo del título del hero.', verbose_name='Texto del hero'),
        ),
        migrations.AlterField(
            model_name='homecontent',
            name='titulo',
            field=models.CharField(help_text='Título grande (H1) en la parte superior del Home.', max_length=300, verbose_name='Título del hero'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='color',
            field=models.CharField(choices=[('primary', 'Primary (azul)'), ('secondary', 'Secondary (morado)')], default='primary', help_text='Color del número. Alterna primary/secondary entre estadísticas para dar contraste visual.', max_length=10),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='etiqueta',
            field=models.CharField(help_text='Texto debajo del número, ej: Certificaciones, Sistemas críticos.', max_length=100),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden de aparición, de izquierda a derecha (menor primero).'),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='sufijo',
            field=models.CharField(blank=True, help_text='Va pegado al número, ej: +, %. Déjalo vacío si no aplica.', max_length=5),
        ),
        migrations.AlterField(
            model_name='homestat',
            name='valor',
            field=models.FloatField(help_text='Número que se anima al cargar la página. Ej: 12, 20, 99.9.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(help_text='Cuerpo completo del artículo en formato Markdown: usa "## Subtítulo" para encabezados, "**texto**" para negrita, "> texto" para citas destacadas, y "- item" para listas.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='destacado_home',
            field=models.BooleanField(default=False, help_text='Se muestra en la sección "Del blog" del Home (máx. 3; si marcas más, se ordenan por fecha).', verbose_name='Destacado en Home'),
        ),
        migrations.AlterField(
            model_name='post',
            name='extracto',
            field=models.TextField(help_text='Resumen corto (1-2 líneas) mostrado en la tarjeta del listado y en "Del blog" del Home.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_publicacion',
            field=models.DateField(help_text='Define el orden del listado (más reciente primero) y se muestra en la tarjeta y el detalle.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, help_text='Imagen de portada: aparece en la tarjeta del listado, en "Del blog" del Home, y arriba del detalle. Si se deja vacía, se muestra un recuadro gris de reemplazo.', null=True, upload_to='blog/portadas/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='lectura_min',
            field=models.PositiveIntegerField(default=5, help_text='Se muestra junto a la fecha, ej: "8 min".', verbose_name='Minutos de lectura'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pilar',
            field=models.CharField(choices=[('Arquitectura', 'Arquitectura'), ('Data Science e IA', 'Data Science e IA'), ('Pensamiento Sistémico', 'Pensamiento Sistémico')], help_text='Categoría temática del artículo. Funciona como filtro en el listado del Blog y define el color de la etiqueta.', max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=True, help_text='Desmárcalo para ocultar el artículo de todo el sitio sin borrarlo.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera solo a partir del título si lo dejas vacío. Define la URL: /blog/este-texto/', max_length=240, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Temas separados por coma, ej: Arquitectura, Sistemas críticos. Se muestran al final del artículo.', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(help_text='Título del artículo. Aparece en la tarjeta del listado y como encabezado del detalle.', max_length=220),
        ),
        migrations.AlterField(
            model_name='project',
            name='anio',
            field=models.PositiveIntegerField(help_text='Año del proyecto. Define el orden del listado (más reciente primero).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='arquitectura_texto',
            field=models.TextField(blank=True, help_text='Sección "Arquitectura" del detalle. Si se deja vacío, esa sección se oculta (y también la de "Arquitectura" en el Home si este es el proyecto ancla).', verbose_name='Arquitectura (texto)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categoria',
            field=models.CharField(help_text='Etiqueta corta, ej: Data, ML Ops, Systems. También funciona como filtro en el listado de Proyectos.', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='destacado_home',
            field=models.BooleanField(default=False, help_text='Se muestra en la sección "Proyectos destacados" del Home (máx. 3; si marcas más, se ordenan por año).', verbose_name='Destacado en Home'),
        ),
        migrations.AlterField(
            model_name='project',
            name='es_ancla',
            field=models.BooleanField(default=False, help_text='Actívalo solo en UN proyecto a la vez: ese es el que se muestra en la sección "Caso ancla" del Home (usa su título, año, problema, arquitectura, resultado, métricas e imagen hero).', verbose_name='Proyecto ancla'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text='Si se llena: botón "Código" en el detalle + ícono de GitHub en la tarjeta del listado.', verbose_name='URL de GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen_arquitectura',
            field=models.ImageField(blank=True, help_text='Imagen o diagrama para la sección "Arquitectura" del detalle. Opcional.', null=True, upload_to='proyectos/arquitectura/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen_card',
            field=models.ImageField(blank=True, help_text='Imagen de la tarjeta en el listado de Proyectos y en "Proyectos destacados" del Home. Si se deja vacía, se muestra un recuadro gris de reemplazo.', null=True, upload_to='proyectos/cards/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='imagen_hero',
            field=models.ImageField(blank=True, help_text='Imagen grande en la parte superior del detalle. También aparece en "Caso ancla" del Home si este es el proyecto ancla.', null=True, upload_to='proyectos/hero/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='industria',
            field=models.CharField(help_text='Etiqueta corta, ej: Fintech, Salud, Retail. También funciona como filtro en el listado.', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='notebook_url',
            field=models.URLField(blank=True, help_text='Si se llena: botón "Notebook" en el detalle + ícono de notebook en la tarjeta del listado.', verbose_name='URL de notebook'),
        ),
        migrations.AlterField(
            model_name='project',
            name='problema',
            field=models.TextField(blank=True, help_text='Sección "El problema" del detalle. Si se deja vacío, esa sección se oculta (y también la de "Problema" en el Home si este es el proyecto ancla).'),
        ),
        migrations.AlterField(
            model_name='project',
            name='publicado',
            field=models.BooleanField(default=True, help_text='Desmárcalo para ocultar el proyecto de todo el sitio sin borrarlo.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='resultado',
            field=models.CharField(help_text='Resumen corto (1-2 líneas) para la tarjeta del listado y para "Proyectos destacados" del Home.', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='resumen',
            field=models.TextField(help_text='Resumen largo mostrado como párrafo principal en la parte superior de la página de detalle.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='Se genera solo a partir del título si lo dejas vacío. Define la URL: /proyectos/este-texto/', max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='solucion',
            field=models.TextField(blank=True, help_text='Sección "La solución" del detalle (junto con los pasos del enfoque, abajo). Si se deja vacío, se oculta.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.CharField(blank=True, help_text='Tecnologías separadas por coma, ej: Python, Kubernetes, MLflow. Aparecen como etiquetas en "Stack" del detalle.', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='titulo',
            field=models.CharField(help_text='Nombre del proyecto. Aparece como título en la tarjeta del listado y en la página de detalle.', max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='web_url',
            field=models.URLField(blank=True, help_text='Si se llena: botón "Ver demo" en el detalle + ícono de globo en la tarjeta del listado.', verbose_name='URL de demo'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen para la sección "Galería" del detalle.', null=True, upload_to='proyectos/galeria/'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden de aparición (menor primero).'),
        ),
        migrations.AlterField(
            model_name='projectgalleryimage',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Descripción de la imagen. Se usa como texto alternativo, y como recuadro de reemplazo si no subes imagen.', max_length=120),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='etiqueta',
            field=models.CharField(help_text='Descripción debajo del valor, ej: Uptime, Registros/día. Se muestra en la tarjeta del listado, el panel de métricas del detalle, y en "Caso ancla" del Home si este es el proyecto ancla.', max_length=80),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden de aparición (menor primero).'),
        ),
        migrations.AlterField(
            model_name='projectmetric',
            name='valor',
            field=models.CharField(help_text='Número o texto corto, ej: 99.9%, 2M+, Nivel 3.', max_length=40),
        ),
        migrations.AlterField(
            model_name='projectresultado',
            name='etiqueta',
            field=models.CharField(help_text='Descripción del resultado, ej: Tiempo de despliegue de un nuevo modelo. Se muestra en la sección "Resultados e impacto" del detalle.', max_length=160),
        ),
        migrations.AlterField(
            model_name='projectresultado',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden de aparición (menor primero).'),
        ),
        migrations.AlterField(
            model_name='projectresultado',
            name='valor',
            field=models.CharField(help_text='Número o texto corto, ej: −82%, 3.2M, $0.', max_length=40),
        ),
        migrations.AlterField(
            model_name='projectstep',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden de aparición (menor primero).'),
        ),
        migrations.AlterField(
            model_name='projectstep',
            name='texto',
            field=models.TextField(help_text='Un paso del "Enfoque", dentro de la sección "La solución" del detalle. Se numera automáticamente (1, 2, 3…) según el orden.'),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='categoria',
            field=models.CharField(help_text='Nombre del grupo, ej: Data & IA, Infraestructura.', max_length=150),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='items',
            field=models.CharField(help_text='Habilidades separadas por coma, ej: Python, PyTorch, MLOps. Cada una se muestra como una etiqueta.', max_length=500),
        ),
        migrations.AlterField(
            model_name='skillgroup',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden de los grupos (menor primero, de arriba a abajo).'),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='contexto',
            field=models.CharField(help_text='Contexto corto entre guiones, ej: Automatización industrial (HVAC).', max_length=150),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='logro',
            field=models.TextField(help_text='Descripción del logro o actividad principal de esa etapa.'),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Controla el orden en la línea de tiempo (menor primero, de arriba a abajo).'),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='periodo',
            field=models.CharField(help_text='Rango de años, ej: 2004 — 2013, o 2021 — presente.', max_length=50),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='rol',
            field=models.CharField(help_text='Puesto o rol durante ese periodo.', max_length=150),
        ),
    ]
