# Generated by Django 5.2.15 on 2026-07-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aboutcontent_badge_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='empresa',
            field=models.CharField(blank=True, help_text='Empresa u organización donde ocupaste ese rol.', max_length=150),
        ),
    ]
