# Generated by Django 5.2.15 on 2026-07-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_contexto_to_responsabilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineentry',
            name='caso_exito',
            field=models.TextField(blank=True, help_text='Caso de éxito concreto de esa etapa. Opcional — si está vacío no se muestra en la página.'),
        ),
        migrations.AlterField(
            model_name='timelineentry',
            name='logro',
            field=models.TextField(blank=True, help_text='Logros, resultados o momentos clave de esa etapa. Opcional — si está vacío no se muestra en la página.'),
        ),
    ]
