# Generated by Django 5.2.15 on 2026-07-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_certification_periodo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_programada',
            field=models.DateTimeField(blank=True, help_text='Opcional. Si se define, el artículo se publicará automáticamente en esa fecha y hora (hora del servidor, UTC). Deja "Publicado" desmarcado para que el sistema lo active solo.', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='publicado',
            field=models.BooleanField(default=False, help_text='Desmárcalo para ocultar el artículo de todo el sitio sin borrarlo.'),
        ),
    ]
