# Generated by Django 5.2.15 on 2026-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_fecha_programada_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pilar',
            field=models.CharField(help_text='Categoría temática del artículo. Funciona como filtro en el listado del Blog y define el color de la etiqueta.', max_length=80),
        ),
    ]
